#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

PYTHON_BIN="${PYTHON_BIN:-/home/ljh/anaconda3/envs/vila_mil/bin/python}"
DATA_ROOT_DIR="${DATA_ROOT_DIR:-/xiangmu/data/VILMIL}"
DATA_FOLDER_S="${DATA_FOLDER_S:-features_biomedclip_5x}"
DATA_FOLDER_L="${DATA_FOLDER_L:-features_biomedclip_20x}"
CSV_PATH="${CSV_PATH:-${ROOT_DIR}/dataset_csv/all_data.csv}"
SPLIT_DIR="${SPLIT_DIR:-${ROOT_DIR}/splits/adenocarcinoma/task_adenocarcinoma_strictcv_100}"
FOLD="${FOLD:-0}"
SPLIT="${SPLIT:-test}"
OUTPUT_DIR="${OUTPUT_DIR:-${ROOT_DIR}/results_stage42/cgsp_anchor_selection_audit}"
STAGE41_MANIFEST="${STAGE41_MANIFEST:-${ROOT_DIR}/results_stage41/low_high_coordinate_audit/stage41_manifest.json}"
CONCEPT_PROMPT_PATH="${CONCEPT_PROMPT_PATH:-${ROOT_DIR}/dataset_csv/private_lung_concept_prompt_pool_stage2_core12.json}"
CHECKPOINT_PATH="${CHECKPOINT_PATH:-}"
MAX_SLIDES="${MAX_SLIDES:-0}"
LOW_PATCH_SIZE="${LOW_PATCH_SIZE:-256}"
HIGH_PATCH_SIZE="${HIGH_PATCH_SIZE:-256}"
BBOX_EXPAND_VALUES="${BBOX_EXPAND_VALUES:-1.0,1.5,2.0,3.0}"
PROPOSAL_RADIUS="${PROPOSAL_RADIUS:-512}"
NMS_RADIUS="${NMS_RADIUS:-512}"
NUM_ANCHORS="${NUM_ANCHORS:-16}"
CANDIDATE_TOP_L="${CANDIDATE_TOP_L:-64}"
TOP_G_CONCEPTS="${TOP_G_CONCEPTS:-8}"
PER_CONCEPT_TOP_M="${PER_CONCEPT_TOP_M:-4}"
PROMPT_TOPK="${PROMPT_TOPK:-3}"
MARGIN_WEIGHT="${MARGIN_WEIGHT:-0.5}"
HIGH_CHILD_TOP_M="${HIGH_CHILD_TOP_M:-16}"
NUM_EXAMPLES="${NUM_EXAMPLES:-30}"
SEED="${SEED:-1}"

CMD=(
    "${PYTHON_BIN}" "scripts/analysis/build_stage42_cgsp_anchor_selection_audit.py"
    "--data_root_dir" "${DATA_ROOT_DIR}"
    "--data_folder_s" "${DATA_FOLDER_S}"
    "--data_folder_l" "${DATA_FOLDER_L}"
    "--csv_path" "${CSV_PATH}"
    "--split_dir" "${SPLIT_DIR}"
    "--fold" "${FOLD}"
    "--split" "${SPLIT}"
    "--output_dir" "${OUTPUT_DIR}"
    "--stage41_manifest" "${STAGE41_MANIFEST}"
    "--concept_prompt_path" "${CONCEPT_PROMPT_PATH}"
    "--checkpoint_path" "${CHECKPOINT_PATH}"
    "--max_slides" "${MAX_SLIDES}"
    "--low_patch_size" "${LOW_PATCH_SIZE}"
    "--high_patch_size" "${HIGH_PATCH_SIZE}"
    "--bbox_expand_values" "${BBOX_EXPAND_VALUES}"
    "--proposal_radius" "${PROPOSAL_RADIUS}"
    "--nms_radius" "${NMS_RADIUS}"
    "--num_anchors" "${NUM_ANCHORS}"
    "--candidate_top_l" "${CANDIDATE_TOP_L}"
    "--top_g_concepts" "${TOP_G_CONCEPTS}"
    "--per_concept_top_m" "${PER_CONCEPT_TOP_M}"
    "--prompt_topk" "${PROMPT_TOPK}"
    "--margin_weight" "${MARGIN_WEIGHT}"
    "--high_child_top_m" "${HIGH_CHILD_TOP_M}"
    "--num_examples" "${NUM_EXAMPLES}"
    "--seed" "${SEED}"
)

printf 'Running Step42 CGSP anchor selection audit:\n'
printf '  %q' "${CMD[@]}"
printf '\n'

"${CMD[@]}"
